spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker_dev
    username: postgres
    password: postgres

  jpa:
    show-sql: true

logging:
  level:
    com.financetracker: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
